platform :ios, '11.0'

target 'HolyWater-Test' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'RxDataSources', '~> 5.0'
  pod 'FirebaseFirestore'
  pod 'FirebaseRemoteConfig'
  pod 'SDWebImage'

end
